<script setup lang="ts">
import { computed,onMounted,onUnmounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { cancelJob,deleteMeeting,listJobs,listMeetings,retryJob,searchMeetings,type Job,type Meeting } from '../api/product'
import { fmtDate,fmtClock } from '../utils/format'
import { useDialog } from '../composables/useDialog'

const router=useRouter(),{t}=useI18n(),dialog=useDialog()
const items=ref<Meeting[]>([]),jobs=ref<Job[]>([]),q=ref(''),hits=ref<Array<{segment_id:number;meeting_id:string;meeting_title:string;text:string}>>([]),loading=ref(true),searching=ref(false),error=ref(''),acting=ref('')
const hasQuery=computed(()=>Boolean(q.value.trim()))
const jobMap=computed(()=>new Map(jobs.value.map(job=>[job.meeting_id,job])))
let timer:number|undefined
// 轮询仅在存在处理中(processing 会议 / queued|running job)时启动,
// 处理完成自动停 — 避免常驻轮询打满每小时速率上限(1000/小时)。
const POLL_INTERVAL=2500
function hasActiveProcessing():boolean{
  return items.value.some(m=>m.status==='processing')||jobs.value.some(j=>['queued','running'].includes(j.status))
}
function startPollingIfNeeded(){if(timer===undefined&&hasActiveProcessing()){timer=window.setInterval(()=>void load(true),POLL_INTERVAL)}}
function stopPollingIfNeeded(){if(timer!==undefined&&(!hasActiveProcessing())){window.clearInterval(timer);timer=undefined}}
async function load(silent=false){if(!silent)loading.value=true;try{const [meetings,resultJobs]=await Promise.all([listMeetings(),listJobs()]);items.value=meetings.items;jobs.value=resultJobs.items;error.value=''}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{loading.value=false}startPollingIfNeeded();stopPollingIfNeeded()}
async function search(){if(!q.value.trim()){hits.value=[];return}searching.value=true;try{hits.value=(await searchMeetings(q.value.trim())).hits}finally{searching.value=false}}
function clearSearch(){q.value='';hits.value=[]}
async function remove(m:Meeting){const ok=await dialog.showConfirm({title:t('product.meetings.deleteTitle'),message:t('product.meetings.deleteConfirm',{title:m.title}),confirmText:t('product.meetings.delete'),cancelText:t('btn.cancel'),danger:true});if(!ok)return;await deleteMeeting(m.id);await load()}
async function actJob(job:Job){acting.value=job.id;try{job.status==='failed'||job.status==='cancelled'?await retryJob(job.id):await cancelJob(job.id);await load(true)}finally{acting.value=''}}
onMounted(()=>{void load()});onUnmounted(()=>{if(timer!==undefined)window.clearInterval(timer)})
</script>
<template><section class="product-page"><div class="page-head"><div><div class="eyebrow">{{t('product.meetings.eyebrow')}}</div><h1>{{t('product.meetings.title')}}</h1><p>{{t('product.meetings.lead')}}</p></div><button class="primary-action" @click="router.push({name:'home'})">＋ {{t('product.meetings.new')}}</button></div>
  <form class="searchbox" role="search" @submit.prevent="search"><input v-model="q" :aria-label="t('product.meetings.searchPlaceholder')" :placeholder="t('product.meetings.searchPlaceholder')"><button v-if="hasQuery" type="button" class="clear" :aria-label="t('product.meetings.clearSearch')" @click="clearSearch">×</button><button class="search" :disabled="searching">{{searching?t('product.meetings.searching'):t('product.meetings.search')}}</button></form>
  <div v-if="hasQuery && !searching" class="search-summary">{{t('product.meetings.results',{count:hits.length})}}</div>
  <div v-if="hits.length" class="results"><button v-for="h in hits" :key="`${h.meeting_id}-${h.segment_id}`" @click="router.push({name:'meeting-detail',params:{id:h.meeting_id},query:{segment:h.segment_id}})"><b>{{h.meeting_title}}</b><span>{{h.text}}</span><i>→</i></button></div>
  <div v-if="loading" class="state-card">{{t('common.loading')}}</div><div v-else-if="error" class="state-card error" role="alert"><b>{{t('product.common.loadFailed')}}</b><span>{{error}}</span><button @click="load()">{{t('product.common.retry')}}</button></div>
  <div v-else class="meeting-list"><article v-for="m in items" :key="m.id" tabindex="0" @click="router.push({name:'meeting-detail',params:{id:m.id}})" @keydown.enter="router.push({name:'meeting-detail',params:{id:m.id}})"><div class="status" :class="m.status">{{t(`product.meeting.status.${m.status}`)}}</div><div class="meeting-copy"><h3>{{m.title}}</h3><p>{{t(`product.meeting.source.${m.source}`)}} · {{fmtClock(m.duration_sec||0)}} · {{fmtDate(m.created_at)}}</p><div v-if="jobMap.get(m.id)&&['queued','running'].includes(jobMap.get(m.id)!.status)" class="processing-row"><div><i :style="{width:`${jobMap.get(m.id)!.progress}%`}"/></div><span>{{jobMap.get(m.id)!.stage}} · {{jobMap.get(m.id)!.progress}}%</span><button :disabled="acting===jobMap.get(m.id)!.id" @click.stop="actJob(jobMap.get(m.id)!)">{{t('product.tasks.cancel')}}</button></div><div v-else-if="jobMap.get(m.id)&&['failed','cancelled'].includes(jobMap.get(m.id)!.status)" class="processing-row failed"><span>{{jobMap.get(m.id)!.error_message||t(`product.job.${jobMap.get(m.id)!.status}`)}}</span><button :disabled="acting===jobMap.get(m.id)!.id" @click.stop="actJob(jobMap.get(m.id)!)">{{t('product.tasks.retry')}}</button></div><small v-if="m.error_message&&!jobMap.get(m.id)">{{m.error_message}}</small></div><span class="open">→</span><button class="delete" :aria-label="t('product.meetings.delete')" @click.stop="remove(m)">{{t('product.meetings.delete')}}</button></article><div v-if="!items.length" class="state-card"><b>{{t('product.meetings.emptyTitle')}}</b><span>{{t('product.meetings.empty')}}</span><button @click="router.push({name:'home'})">{{t('product.meetings.new')}}</button></div></div>
</section></template>
<style scoped>.searchbox{display:flex;max-width:760px;margin-bottom:10px;position:relative}.searchbox input{flex:1;background:var(--ink-2);border:1px solid var(--border);padding:13px 44px 13px 15px;border-radius:8px 0 0 8px}.searchbox input:focus{border-color:var(--amber)}.searchbox .search{background:var(--amber);color:#160d09;padding:0 20px;border-radius:0 8px 8px 0;font-weight:700}.searchbox .clear{position:absolute;right:92px;top:7px;width:32px;height:32px;color:var(--text-3)}.search-summary{margin:12px 0;color:var(--text-3);font:10px var(--mono)}.results{display:grid;gap:7px;margin:0 0 24px;padding:12px;background:var(--ink-2);border:1px solid var(--border-soft);border-radius:10px}.results button{display:grid;grid-template-columns:180px 1fr auto;gap:16px;text-align:left;padding:10px;border-radius:6px}.results button:hover{background:var(--ink-3)}.results span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--text-2)}.results i{color:var(--amber);font-style:normal}.meeting-list{display:grid;gap:8px;margin-top:20px}.meeting-list article{display:grid;grid-template-columns:80px 1fr auto auto;align-items:center;gap:18px;padding:18px 20px;background:var(--ink-2);border:1px solid var(--border-soft);border-radius:9px;cursor:pointer}.meeting-list article:hover,.meeting-list article:focus{border-color:var(--border);background:var(--ink-3);outline:none}.status{font:9px var(--mono);color:var(--text-3);text-transform:uppercase}.status.ready{color:var(--green)}.status.processing{color:var(--teal)}.status.failed{color:var(--red)}.meeting-copy h3{font-size:15px}.meeting-copy p{color:var(--text-3);font:10px var(--mono);margin-top:4px}.meeting-copy small{display:block;color:var(--red);margin-top:6px}.open{color:var(--amber);font-size:18px}.delete{opacity:0;color:var(--red);font:10px var(--mono)}article:hover .delete,article:focus .delete,.delete:focus{opacity:1}.state-card{min-height:220px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;text-align:center;color:var(--text-3);border:1px dashed var(--border);border-radius:12px}.state-card b{color:var(--text);font:22px var(--serif)}.state-card button{color:var(--amber)}.state-card.error b{color:var(--red)}@media(max-width:700px){.results button{grid-template-columns:1fr}.results span{white-space:normal}.meeting-list article{grid-template-columns:62px 1fr auto}.open{display:none}.delete{opacity:1}}</style>
