<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { assignSegmentSpeaker,confirmSpeaker,downloadMeeting,generateMeetingNote,getMeeting,getMeetingAudioUrl,listPeople,reprocessMeeting,saveMeetingNote,updateMeeting,updateSegmentText,type MeetingDetail,type Person,type Segment } from '../api/product'
import { fmtSec } from '../utils/format'

const route=useRoute(),{t}=useI18n(),detail=ref<MeetingDetail|null>(null),people=ref<Person[]>([]),loadError=ref('')
const tab=ref<'transcript'|'notes'|'export'>('transcript'),saving=ref(''),audioUrl=ref('')
const player=ref<HTMLAudioElement|null>(null),selected=ref(new Set<number>()),editingId=ref<number|null>(null),draft=ref('')
const selectedCount=computed(()=>selected.value.size)
const noteType=ref<'summary'|'minutes'|'actions'>('summary'),noteDraft=ref(''),noteBusy=ref(false)
const titleEditing=ref(false),titleDraft=ref(''),titleSaving=ref(false)
const reprocessing=ref(false)
const currentNote=computed(()=>detail.value?.notes.find(n=>n.note_type===noteType.value))
const manifest=computed(()=>detail.value?.meeting.processing_manifest)
const transcriptState=computed(()=>detail.value?.meeting.transcript_state||'unknown')
const isRefining=computed(()=>detail.value?.meeting.status==='processing')
const refinementProgress=computed(()=>detail.value?.processing_job?.progress??0)
function refinementStage(){const stage=detail.value?.processing_job?.stage||'queued';const key=`product.job.stage.${stage}`;const translated=t(key);return translated===key?stage:translated}
function noteSource(source:string){if(source==='manual')return t('product.detail.manual');if(source==='llm')return t('product.detail.aiGenerated');if(source==='extractive-fallback')return t('product.detail.localGenerated');return source}
function manifestValue(value?:string){return value||t('product.detail.provenanceUnavailable')}
function alignmentLabel(value?:string){if(!value)return t('product.detail.provenanceUnavailable');const known:Record<string,string>={native:'product.detail.alignmentNative','word-timestamps':'product.detail.alignmentWords','word_timestamp':'product.detail.alignmentWords','word-overlap':'product.detail.alignmentWords','segment-overlap':'product.detail.alignmentSegment','pyannote-segment-overlap':'product.detail.alignmentSegment',none:'product.detail.alignmentNone',anonymous:'product.detail.alignmentNone'};return known[value]?t(known[value]):value}

async function load(){try{detail.value=await getMeeting(String(route.params.id));people.value=(await listPeople()).items;loadError.value=''}catch(e){loadError.value=e instanceof Error?e.message:String(e)}}
async function loadAudio(){try{audioUrl.value=await getMeetingAudioUrl(String(route.params.id))}catch{audioUrl.value=''}}
async function assignIdentity(speakerId:string,personId:string){if(isRefining.value)return;saving.value=speakerId;try{await confirmSpeaker(String(route.params.id),speakerId,personId||null);await load()}finally{saving.value=''}}
async function confirmSuggested(speakerId:string,personId?:string){if(personId)await assignIdentity(speakerId,personId)}
function segmentSpeaker(segment:Segment){return ['auto_matched','confirmed'].includes(segment.identity_status||'')&&segment.person_name?segment.person_name:(segment.speaker_label||t('product.detail.unknown'))}
async function reprocess(){reprocessing.value=true;try{await reprocessMeeting(String(route.params.id));await load()}catch(e){window.toast?.(`${t('product.detail.reprocessFailed')}: ${e instanceof Error?e.message:e}`,'error')}finally{reprocessing.value=false}}
function seek(segment:Segment){if(player.value){player.value.currentTime=segment.start_time;void player.value.play()}}
function beginEdit(segment:Segment){if(isRefining.value)return;editingId.value=segment.id;draft.value=segment.text}
function cancelEdit(){editingId.value=null;draft.value=''}
async function saveEdit(segment:Segment){const text=draft.value.trim();if(!text)return;await updateSegmentText(String(route.params.id),segment.id,text);segment.text=text;(segment as any).manually_edited=1;cancelEdit()}
function toggle(id:number){if(isRefining.value)return;const next=new Set(selected.value);next.has(id)?next.delete(id):next.add(id);selected.value=next}
async function batchAssign(speakerId:string){if(!selected.value.size||!speakerId)return;await assignSegmentSpeaker(String(route.params.id),[...selected.value],speakerId==='__clear__'?null:speakerId);selected.value=new Set();await load()}
function openNote(type:'summary'|'minutes'|'actions'){noteType.value=type;noteDraft.value=detail.value?.notes.find(n=>n.note_type===type)?.content||''}
async function generateNote(){noteBusy.value=true;try{const note=await generateMeetingNote(String(route.params.id),noteType.value);noteDraft.value=note.content;await load()}finally{noteBusy.value=false}}
async function saveNote(){if(!noteDraft.value.trim())return;noteBusy.value=true;try{await saveMeetingNote(String(route.params.id),noteType.value,noteDraft.value.trim());await load()}finally{noteBusy.value=false}}
function beginTitleEdit(){if(!detail.value)return;titleDraft.value=detail.value.meeting.title;titleEditing.value=true}
async function saveTitle(){const title=titleDraft.value.trim();if(!title||!detail.value)return;titleSaving.value=true;try{detail.value.meeting=await updateMeeting(detail.value.meeting.id,title);titleEditing.value=false}finally{titleSaving.value=false}}

let refreshTimer:ReturnType<typeof setInterval>|null=null
onMounted(async()=>{await Promise.all([load(),loadAudio()]);refreshTimer=setInterval(()=>{if(detail.value?.meeting.status==='processing')void load()},2000);const segment=Number(route.query.segment);if(segment){requestAnimationFrame(()=>document.getElementById(`segment-${segment}`)?.scrollIntoView({behavior:'smooth',block:'center'}))}})
onBeforeUnmount(()=>{if(refreshTimer)clearInterval(refreshTimer);if(audioUrl.value)URL.revokeObjectURL(audioUrl.value)})
</script>

<template><section v-if="detail" class="product-page detail-page">
  <header class="detail-head"><div><div class="eyebrow">{{t(detail.meeting.source==='live'?'product.detail.liveRecord':'product.detail.uploadRecord')}}</div><div v-if="titleEditing" class="title-editor"><input v-model="titleDraft" maxlength="200" autofocus @keyup.enter="saveTitle" @keyup.esc="titleEditing=false"><button :disabled="titleSaving" @click="saveTitle">{{t('product.detail.saveTitle')}}</button><button @click="titleEditing=false">{{t('product.detail.cancel')}}</button></div><button v-else class="title-button" :title="t('product.detail.rename')" @click="beginTitleEdit"><h1>{{detail.meeting.title}}</h1><span>✎</span></button><p>{{t('product.detail.meta',{segments:detail.segments.length,speakers:detail.speakers.length})}} <span class="transcript-state" :class="transcriptState">{{t(`product.detail.state.${transcriptState}`)}}</span></p></div><div class="tabs" role="tablist"><button :class="{active:tab==='transcript'}" role="tab" :aria-selected="tab==='transcript'" @click="tab='transcript'">{{t('product.detail.transcript')}}</button><button :class="{active:tab==='notes'}" role="tab" :aria-selected="tab==='notes'" @click="tab='notes';openNote(noteType)">{{t('product.detail.outputs')}}</button><button :class="{active:tab==='export'}" role="tab" :aria-selected="tab==='export'" @click="tab='export'">{{t('product.detail.export')}}</button></div></header>
  <audio v-if="audioUrl" ref="player" class="player" :src="audioUrl" controls preload="metadata" />
  <aside v-if="isRefining" class="refining"><strong>{{t('product.detail.refiningTitle')}}</strong><p>{{t('product.detail.refiningHint')}}</p><div class="refinement-progress"><i :style="{width:`${refinementProgress}%`}"/></div><small>{{t('product.detail.refiningProgress',{stage:refinementStage(),progress:refinementProgress})}}</small><p class="draft-lock">{{t('product.detail.draftLocked')}}</p></aside>
  <aside v-else-if="detail.meeting.status==='failed'" class="capability-warning"><div><strong>{{t('product.detail.refinementFailedTitle')}}</strong><p>{{t('product.detail.refinementFailedHint')}}</p></div><code v-if="detail.meeting.error_message">{{detail.meeting.error_message}}</code><button :disabled="reprocessing" @click="reprocess">{{reprocessing?t('product.detail.reprocessing'):t('product.detail.reprocess')}}</button></aside>
  <aside v-else-if="detail.meeting.diarization_status==='unavailable'" class="capability-warning"><div><strong>{{t('product.detail.diarizationTitle')}}</strong><p>{{t('product.detail.diarizationUnavailable')}}</p></div><details><summary>{{t('product.detail.diarizationHow')}}</summary><p>{{t('product.detail.diarizationSetup')}}</p><code>{{detail.meeting.diarization_error||'HF_TOKEN'}}</code></details><button :disabled="reprocessing" @click="reprocess">{{reprocessing?t('product.detail.reprocessing'):t('product.detail.reprocess')}}</button></aside>
  <details class="provenance"><summary>{{t('product.detail.provenanceTitle')}}</summary><p>{{t('product.detail.provenanceHint')}}</p><dl><template v-if="manifest"><dt>{{t('product.detail.provenanceStrategy')}}</dt><dd>{{manifestValue(manifest.strategy)}}</dd><dt>{{t('product.detail.provenanceAsr')}}</dt><dd>{{manifestValue(manifest.asr?.model||manifest.asr?.engine)}}</dd><dt>{{t('product.detail.provenanceTiming')}}</dt><dd>{{manifestValue(manifest.asr?.timestamp_granularity)}}</dd><dt>{{t('product.detail.provenanceDiarization')}}</dt><dd>{{manifestValue(manifest.diarization?.provider)}}</dd><dt>{{t('product.detail.provenanceAlignment')}}</dt><dd>{{alignmentLabel(manifest.diarization?.alignment)}}</dd><dt>{{t('product.detail.provenanceIdentity')}}</dt><dd>{{manifestValue(manifest.speaker_identity?.model_id||manifest.speaker_identity?.engine)}}</dd></template><template v-else><dt>{{t('product.detail.provenanceState')}}</dt><dd>{{t('product.detail.provenanceLegacy')}}</dd></template></dl></details>
  <template v-if="tab==='transcript'">
    <aside v-if="detail.speakers.length" class="speaker-confirm"><h2>{{t('product.detail.confirmSpeakers')}}</h2><p>{{t('product.detail.confirmHint')}}</p><p class="anonymous-hint">{{t('product.detail.anonymousHint')}}</p><label v-for="s in detail.speakers" :key="s.id"><span>{{s.label}}</span><select :value="s.person_id||''" :disabled="isRefining||saving===s.id" @change="assignIdentity(s.id,($event.target as HTMLSelectElement).value)"><option value="">{{t('product.detail.unconfirmed')}}</option><option v-for="p in people" :key="p.id" :value="p.id">{{p.name}}</option></select><em v-if="s.identity_status==='confirmed'">{{t('product.detail.identityConfirmed')}}</em><em v-else-if="s.identity_status==='auto_matched'">{{t('product.detail.identityAutoMatched',{score:Math.round((s.confidence||0)*100)})}}</em><template v-else-if="s.identity_status==='suggested'&&s.person_id"><em>{{t('product.detail.identitySuggested',{score:Math.round((s.confidence||0)*100)})}}</em><button :disabled="isRefining||saving===s.id" @click="confirmSuggested(s.id,s.person_id)">{{t('product.detail.confirmSuggestion')}}</button></template></label></aside>
    <div v-if="selectedCount&&!isRefining" class="batch"><b>{{t('product.detail.selected',{count:selectedCount})}}</b><select @change="batchAssign(($event.target as HTMLSelectElement).value)"><option value="">{{t('product.detail.assignTo')}}</option><option v-for="s in detail.speakers" :key="s.id" :value="s.id">{{s.person_name||s.label}}</option><option value="__clear__">{{t('product.detail.clearSpeaker')}}</option></select><button @click="selected=new Set()">{{t('product.detail.cancelSelection')}}</button></div>
    <main class="transcript"><article v-for="s in detail.segments" :id="`segment-${s.id}`" :key="s.id" :class="{selected:selected.has(s.id),manual:s.manually_edited}"><input type="checkbox" :disabled="isRefining" :checked="selected.has(s.id)" @change="toggle(s.id)"><button class="who" @click="seek(s)"><b>{{segmentSpeaker(s)}}</b><span v-if="s.identity_status==='auto_matched'" class="identity-badge">{{t('product.detail.identityAutoBadge')}}</span><time>{{fmtSec(s.start_time)}}</time></button><div v-if="editingId===s.id" class="editor"><textarea v-model="draft" rows="3" @keydown.ctrl.enter="saveEdit(s)"/><div><button @click="cancelEdit">{{t('product.detail.cancel')}}</button><button class="save" @click="saveEdit(s)">{{t('product.detail.saveEdit')}}</button></div></div><p v-else @dblclick="beginEdit(s)">{{s.text}}<span v-if="s.manually_edited" class="corrected">{{t('product.detail.corrected')}}</span><button v-if="!isRefining" class="edit" @click="beginEdit(s)">{{t('product.detail.edit')}}</button></p></article><div v-if="!detail.segments.length" class="empty-state">{{t(detail.meeting.status==='processing'?'product.detail.processing':'product.detail.noTranscript')}}</div></main>
  </template>
  <section v-else-if="tab==='notes'" class="notes-panel"><div class="note-head"><div><h2>{{t('product.detail.outputsTitle')}}</h2><p>{{t('product.detail.outputsHint')}}</p></div><div class="note-types"><button v-for="type in (['summary','actions','minutes'] as const)" :key="type" :class="{active:noteType===type}" @click="openNote(type)">{{t(`product.detail.${type}`)}}</button></div></div><div v-if="!currentNote&&!noteDraft.trim()" class="note-empty"><span>✦</span><h3>{{t(`product.detail.${noteType}Empty`)}}</h3><p>{{isRefining?t('product.detail.draftLocked'):t('product.detail.generateHint')}}</p><button :disabled="isRefining||noteBusy||!detail.segments.length" @click="generateNote">{{noteBusy?t('product.detail.generating'):t('product.detail.generateNow')}}</button></div><template v-else><textarea v-model="noteDraft" rows="18" :disabled="isRefining" :placeholder="t('product.detail.notePlaceholder')"/><footer><span v-if="currentNote">{{t('product.detail.source',{source:noteSource(currentNote.source)})}}</span><button :disabled="isRefining||noteBusy" @click="generateNote">{{t(currentNote?'product.detail.regenerate':'product.detail.generate')}}</button><button class="save" :disabled="isRefining||noteBusy||!noteDraft.trim()" @click="saveNote">{{t('product.detail.saveNote')}}</button></footer></template></section>
  <div v-else class="export-panel"><h2>{{t('product.detail.exportTitle')}}</h2><p>{{t('product.detail.exportHint')}}</p><div><button @click="downloadMeeting(detail.meeting.id,'markdown')"><b>Markdown</b><span>{{t('product.detail.markdownHint')}}</span></button><button @click="downloadMeeting(detail.meeting.id,'srt')"><b>SRT</b><span>{{t('product.detail.srtHint')}}</span></button><button @click="downloadMeeting(detail.meeting.id,'vtt')"><b>WebVTT</b><span>{{t('product.detail.vttHint')}}</span></button><button @click="downloadMeeting(detail.meeting.id,'json')"><b>JSON</b><span>{{t('product.detail.jsonHint')}}</span></button></div></div>
</section><section v-else class="product-page"><div v-if="loadError" class="empty-state detail-error"><b>{{t('product.common.loadFailed')}}</b><span>{{loadError}}</span><button @click="load">{{t('product.common.retry')}}</button></div><div v-else class="empty-state">{{t('product.detail.loading')}}</div></section></template>

<style scoped>
.title-button{display:flex;align-items:center;gap:12px;text-align:left}.title-button span{opacity:0;color:var(--amber)}.title-button:hover span,.title-button:focus span{opacity:1}.title-editor{display:flex;align-items:center;gap:8px;margin:8px 0}.title-editor input{min-width:min(520px,60vw);padding:9px 11px;background:var(--ink-2);border:1px solid var(--amber);border-radius:6px;font:24px var(--serif)}.title-editor button{color:var(--amber);font:10px var(--mono)}.detail-error{display:flex;flex-direction:column;gap:8px}.detail-error b{color:var(--red)}.detail-error button{color:var(--amber)}
.detail-head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--border);padding-bottom:24px}.detail-head h1{font:42px var(--serif);margin:8px 0}.detail-head p,.speaker-confirm p,.export-panel>p{color:var(--text-3)}.tabs{display:flex;gap:20px}.tabs button{padding:9px 0;border-bottom:2px solid transparent}.tabs button.active{color:var(--amber);border-color:var(--amber)}.player{width:100%;margin:18px 0;accent-color:var(--amber)}.speaker-confirm{margin:8px 0 20px;padding:20px;background:var(--ink-2);border-radius:10px}.speaker-confirm h2,.export-panel h2{font:22px var(--serif)}.speaker-confirm label{display:inline-flex;align-items:center;gap:8px;margin:16px 16px 0 0}.speaker-confirm select,.batch select{background:var(--ink-3);color:var(--text);border:1px solid var(--border);padding:7px 10px;border-radius:5px}.batch{position:sticky;top:8px;z-index:3;display:flex;align-items:center;gap:14px;padding:12px 18px;background:var(--gold);color:var(--ink);border-radius:8px}.transcript{max-width:900px;margin:18px auto}.transcript article{display:grid;grid-template-columns:22px 140px 1fr;gap:18px;padding:18px 10px;border-bottom:1px solid var(--border-soft);border-radius:6px}.transcript article.selected{background:var(--amber-soft)}.transcript article.manual{border-left:2px solid var(--teal)}.who{display:flex;flex-direction:column;text-align:left}.who b{color:var(--amber)}time{font:10px var(--mono);color:var(--text-3)}.transcript p{font-size:16px;line-height:1.75}.edit{opacity:0;color:var(--amber);font:10px var(--mono);margin-left:10px}.transcript article:hover .edit{opacity:1}.corrected{color:var(--teal);font:9px var(--mono);margin-left:10px}.editor textarea{width:100%;resize:vertical;background:var(--ink-2);border:1px solid var(--amber);border-radius:6px;padding:10px;line-height:1.6}.editor>div{display:flex;justify-content:flex-end;gap:12px;margin-top:8px}.editor .save{color:var(--amber)}.export-panel{max-width:750px;margin:60px auto}.export-panel>div{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:24px}.export-panel button{padding:20px;background:var(--ink-2);border:1px solid var(--border);border-radius:8px;text-align:left;display:flex;flex-direction:column}.export-panel button:hover{border-color:var(--amber)}.export-panel span{color:var(--text-3);margin-top:4px}@media(max-width:700px){.detail-head{align-items:start;flex-direction:column;gap:20px}.transcript article{grid-template-columns:20px 1fr}.transcript article>p,.editor{grid-column:2}.batch{flex-wrap:wrap}}
.notes-panel{max-width:850px;margin:36px auto}.note-types{display:flex;gap:8px;margin-bottom:12px}.note-types button{padding:8px 13px;border-radius:5px;background:var(--ink-2)}.note-types button.active{background:var(--amber-soft);color:var(--amber)}.notes-panel textarea{width:100%;padding:18px;background:var(--ink-2);border:1px solid var(--border);border-radius:8px;line-height:1.7;resize:vertical}.notes-panel footer{display:flex;justify-content:flex-end;align-items:center;gap:14px;margin-top:12px}.notes-panel footer span{margin-right:auto;color:var(--text-3);font:10px var(--mono)}.notes-panel footer button{color:var(--amber)}.notes-panel footer .save{padding:8px 14px;background:var(--amber);color:var(--ink);border-radius:5px}
.capability-warning{max-width:900px;margin:12px auto;padding:14px 16px;border:1px solid rgba(255,107,53,.45);border-radius:8px;background:var(--amber-soft);color:var(--text-2)}.capability-warning strong{color:var(--amber)}.capability-warning p{margin-top:4px}.capability-warning details{margin-top:9px;padding-top:9px;border-top:1px solid rgba(255,107,53,.2)}.capability-warning summary{cursor:pointer;color:var(--text);font:11px var(--mono)}.capability-warning code{display:block;margin-top:7px;color:var(--text-3);white-space:normal}.note-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:18px}.note-head h2{font:28px var(--serif)}.note-head p{color:var(--text-3);margin-top:5px}.note-head .note-types{margin-bottom:0}.note-empty{min-height:330px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;border:1px dashed var(--border);border-radius:12px;background:var(--ink-2)}.note-empty>span{color:var(--amber);font-size:28px}.note-empty h3{font:25px var(--serif);margin:12px 0 6px}.note-empty p{max-width:520px;color:var(--text-3)}.note-empty button{margin-top:20px;padding:10px 18px;border-radius:7px;background:var(--amber);color:var(--ink);font-weight:700}.note-empty button:disabled{opacity:.4}@media(max-width:700px){.note-head{align-items:flex-start;flex-direction:column}.title-editor{align-items:flex-start;flex-wrap:wrap}.title-editor input{min-width:100%}}
.capability-warning>button{margin-top:12px;padding:8px 13px;border-radius:6px;background:var(--amber);color:var(--ink);font-weight:700}.refining{max-width:900px;margin:12px auto;padding:14px 16px;border-left:2px solid var(--teal);background:var(--teal-soft)}.refining strong{color:var(--teal)}.refining p{margin-top:4px;color:var(--text-2)}.refining small{display:block;margin-top:6px;color:var(--teal);font:10px var(--mono)}.refining .draft-lock{color:var(--text-3);font-size:11px}.refinement-progress{height:4px;margin-top:12px;overflow:hidden;border-radius:999px;background:var(--ink-3)}.refinement-progress i{display:block;height:100%;background:var(--teal);transition:width .25s}.speaker-confirm label em{color:var(--text-3);font:9px var(--mono);font-style:normal}.speaker-confirm label button{padding:6px 9px;border-radius:5px;background:var(--amber);color:var(--ink);font:9px var(--mono)}.identity-badge{width:max-content;padding:2px 5px;border-radius:999px;background:var(--teal-soft);color:var(--teal);font:8px var(--mono)}
.transcript-state{display:inline-block;margin-left:8px;padding:2px 7px;border:1px solid var(--border);border-radius:999px;font:9px var(--mono);color:var(--text-2)}.transcript-state.refined{border-color:rgba(78,205,196,.45);color:var(--teal)}.provenance{max-width:900px;margin:12px auto;padding:12px 16px;border:1px solid var(--border-soft);border-radius:8px;background:var(--ink-2)}.provenance summary{cursor:pointer;color:var(--text-2);font:11px var(--mono)}.provenance>p{margin:8px 0;color:var(--text-3);font-size:11px}.provenance dl{display:grid;grid-template-columns:minmax(100px,160px) 1fr;gap:7px 16px;margin-top:12px}.provenance dt{color:var(--text-3);font:10px var(--mono)}.provenance dd{overflow-wrap:anywhere;color:var(--text-2);font-size:12px}.anonymous-hint{margin-top:6px;color:var(--amber)!important;font-size:11px}
</style>
